import Head from "next/head";
import Homepage from "../components/homepage";

export default function Home() {
  const container = "w-3/4 mx-auto border-2 p-8";
  return (
    <div>
      <Head>
        <title>Rent Now</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </div>
  );
}
